# This Action will build the SDK and if this succeeds, trigger a build on the
# jMonkeyEngine/sdk-update-center repository, so that nbms get built and
# deployed
name: Nightly NBM Deployment

on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Grant execute permission for the scripts
      run: chmod +x gradlew *.sh
      
    - name: Download and build the Engine
      run: ./build_engine.sh
      
    - name: Fix the Engine
      run: ./fix_engine.sh
      
    - name: Build the SDK
      run: ./gradlew buildSdk
    
    - name: Checkout the nightly-trigger repository
      uses: actions/checkout@v2
      with:
        repository: 'jMonkeyEngine/sdk-update-center'
        ref: nightly
        path: nightly
        token: ${{ secrets. UPDATE_CENTER_PAT }}
      
    - name: Setup Git for the commit
      run: git config user.email MeFisto94@users.noreply.github.com && git config user.name MeFisto94
      working-directory: nightly
      
    - name: Overwrite the target file
      run: rm -rf nightly/target && echo 'echo "sdk_sha=${{ github.sha }}" >> $GITHUB_ENV' > nightly/target
      
    - name: Trigger nightly builds
      working-directory: nightly
      run: git add target && git commit -m "Trigger a fresh nightly build for https://github.com/jMonkeyEngine/sdk/commit/${{ github.sha }}" && git push
