# This Action will build the SDK and if this succeeds, create a github release
name: Release Builds
on:
  push:
    tags:
      - "*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11
    - name: Grant execute permission for gradle
      run: chmod +x gradlew
    - name: Build the SDK
      run: ./gradlew buildSdk -Ptag_name=${{ github.ref_name }}
    - name: Build the JDKs
      run: bash download-jdks.sh
      working-directory: jdks
    - name: Override Harness (custom icon)
      run: ./gradlew overrideHarness -Ptag_name=${{ github.ref_name }}
    - name: Build Installers
      run: ant -Dstorepass="$NBM_SIGN_PASS" -Dpack200.enabled=true set-spec-version build-installers unset-spec-version
      env:
        BUILD_X86: true
        BUILD_X64: true
        BUILD_OTHER: true
    - name: Fix Platform Independent Build
      run: ./gradlew fixPlatformIndependent -Ptag_name=${{ github.ref_name }}
    - name: Create Release
      uses: softprops/action-gh-release@v0.1.14

      with:
        files: dist/jmonkeyplatform*.*
        tag_name:  ${{ github.ref }}
        name: Release ${{ github.ref }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
